#lang ivy1.7

include chrono_time
include c_time

#interpret cid -> longbv[1][13][20]
# This file provides the interface to the time interface

# interpret microseconds -> int #bv[32] #intbv[0][2147483647][32] #bv[55]
# interpret milliseconds -> int #bv[32] #intbv[0][2147483647][32] #bv[45]

object time_api = {
     instance c_timer : c_time(microseconds, milliseconds)
     instance chrono_timer : chrono_time(microseconds, milliseconds)
}    