#lang ivy1.7 

include collections

object packet = {
    
    type this 

    instance idx : unbounded_sequence
    instance arr : array(idx,this) 

    # Normal behavior

    action handle(src:ip.endpoint,dst:ip.endpoint,pkt:this) = {
        require false; 
    }

## Man in the middle

    action forward_to_client(src:ip.endpoint,dst:ip.endpoint,pkt:this) = {
        require false; 
    }

    action forward_to_server(src:ip.endpoint,dst:ip.endpoint,pkt:this) = {
        require false; 
    }

    action replay_to_client(src:ip.endpoint,dst:ip.endpoint,pkt:this) = {
        require false; 
    }

    action replay_to_server(src:ip.endpoint,dst:ip.endpoint,pkt:this) = {
        require false; 
    }

## White noise

    # 1. Denial-of-Service (DoS) Attacks

    action flood(src:ip.endpoint,dst:ip.endpoint, pkt:this) = {
        require false; 
    }
}