#lang ivy1.7

include chrono_time_wrapper

module chrono_time(microseconds, milliseconds) = {

    action start
    action timeout
    action now_micros returns (i:microseconds)
    action now_millis returns (i:milliseconds)
    action now_micros_last_bp returns (i:microseconds)
    action now_millis_last_bp returns (i:milliseconds)

    object spec = {
        
    }

    instance impl : chrono_time_wrapper(this)
}
