# PANTHER Ivy Tester Plugin Manifest
name: panther_ivy
version: 1.0.0
type: tester
author: PANTHER Team
description: Ivy-based formal verification tester for protocol compliance testing
license: MIT

# Compatibility
min_panther_version: 1.0.0

# Dependencies
dependencies:
  - name: ivy
    version_spec: ">=1.8.0"
    # External dependency - no plugin_type needed
  
  - name: quic_protocol
    version_spec: ">=1.0.0"
    plugin_type: protocol

# Configuration schema
config_schema:
  timeout:
    type: number
    default: 150
    description: Test execution timeout in seconds (Ivy compilation can be slow)
  
  test:
    type: string
    description: Specific Ivy test to run (e.g., quic_client_test_max)
    required: true
  
  implementation:
    type: object
    properties:
      name:
        type: string
        default: panther_ivy
      type:
        type: string
        enum: ["testers", "TESTERS"]
        default: testers
  
  protocol:
    type: object
    properties:
      name:
        type: string
        default: quic
      version:
        type: string
        default: rfc9000
      role:
        type: string
        enum: ["server", "client"]
  
  ports:
    type: array
    items:
      type: string
    description: Port mappings for the tester

# Default configuration
default_config:
  timeout: 150
  implementation:
    name: panther_ivy
    type: testers
  protocol:
    name: quic
    version: rfc9000

# Supported protocols
supported_protocols:
  - quic

# Capabilities
capabilities:
  - formal_verification
  - protocol_compliance
  - specification_testing
  - adversarial_testing
  - mutation_testing
  - state_machine_verification

# Supported events
supported_events:
  - test_started
  - test_compilation_started
  - test_compilation_completed
  - test_execution_started
  - test_execution_completed
  - assertion_passed
  - assertion_failed
  - test_completed

# Available tests
available_tests:
  - quic_client_test_max
  - quic_server_test_max
  - quic_handshake_test
  - quic_transport_test
  - quic_recovery_test
  - quic_flow_control_test

# Tags
tags:
  - testing
  - formal_verification
  - ivy
  - quic
  - compliance
  - security