#lang ivy1.7

#    Autonomous System (AS)
#       The classic definition of an Autonomous System is a set of routers
#       under a single technical administration, using an interior gateway
#       protocol (IGP) and common metrics to determine how to route
#       packets within the AS, and using an inter-AS routing protocol to
#       determine how to route packets to other ASes.  Since this classic
#       definition was developed, it has become common for a single AS to
#       use several IGPs and, sometimes, several sets of metrics within an
#       AS.  The use of the term Autonomous System stresses the fact that,
#       even when multiple IGPs and metrics are used, the administration
#       of an AS appears to other ASes to have a single coherent interior
#       routing plan, and presents a consistent picture of the
#       destinations that are reachable through it.