#lang ivy1.7

include order
include file
include ip
include apt_endpoint
include ivy_mim

# TODO update packet src port/dst port for invisible on network and host
 
# An ip endpoint for the client to migrate to. TODO

# a socket for the server

var sock_mim_server : stream_data_net.socket
var sock_mim_client : stream_data_net.socket


# Open a server socket to listen on and create an instance of TLS.
# TODO: we should have one instance of TLS per connection

after init {
    malicious_packet_send := false;
    mim_agent.ep_server.interface := ip.veth_ivy;
}


# udp && (udp.srcport == 4443 || udp.dstport == 4443 || udp.srcport == 4440 || udp.dstport == 4440 )