#lang ivy1.7


# Initial state
# -------------

# The history variables are initialized as follows.  Initially, no
# connections have been seen and no packets have been sent or
# acknowledged.


object packet = {
    ...

    object quic_packet = {

        ...

        action forward_to_client(src:ip.endpoint,dst:ip.endpoint,pkt:packet.quic_packet)
        around forward_to_client(src:ip.endpoint,dst:ip.endpoint,pkt:packet.quic_packet) {
            require _generating;
            require pkt.payload.end > 0;
            require mim_agent.nat_configured;
            require src ~= dst;
            ...
            call enqueue_packet(src,dst,pkt);
        }
        
        action forward_to_server(src:ip.endpoint,dst:ip.endpoint,pkt:packet.quic_packet)
        around forward_to_server(src:ip.endpoint,dst:ip.endpoint,pkt:packet.quic_packet) {
            require _generating;
            require pkt.payload.end > 0;
            require mim_agent.nat_configured;
            require src ~= dst;
            ...
            call enqueue_packet(src,dst,pkt);
        }
        
    }

}


function quic_packet_recevied_last_round(C:ip.endpoint) : packet.quic_packet.arr

after receiving_packet(src:ip.endpoint,dst:ip.endpoint,pkt:packet) {
    if some(cf:packet.quic_packet)pkt *> cf {
        quic_packet_recevied_last_round(dst) := quic_packet_recevied_last_round(dst).append(cf);
    }
}