#lang ivy1.7

# Packet protocol state
# ---------------------

object packet = {
    ...

    object ping_packet = {

        ...

        action forward_to_client(src:ip.endpoint,dst:ip.endpoint,pkt:packet.ping_packet)
        around forward_to_client(src:ip.endpoint,dst:ip.endpoint,pkt:packet.ping_packet) {
            # require _generating;
            require pkt.payload.end > 0;
            require mim_agent.nat_configured;
            require is_ping_packet_received(dst,pkt);
            require src ~= dst;
            require dst = mim_agent.ep_client & src = mim_agent.ep_server;
            ...
            call enqueue_packet(src,dst,pkt);
            is_ping_packet_received(dst,pkt) := false;
            ping_packet_forwarded_last_round(dst) := ping_packet_forwarded_last_round(dst) + 1;
        }
        
        action forward_to_server(src:ip.endpoint,dst:ip.endpoint,pkt:packet.ping_packet)
        around forward_to_server(src:ip.endpoint,dst:ip.endpoint,pkt:packet.ping_packet) {
            # require _generating;
            require pkt.payload.end > 0;
            require mim_agent.nat_configured;
            require is_ping_packet_received(dst,pkt);
            require src ~= dst;
            require dst = mim_agent.ep_server & src = mim_agent.ep_client;
            ...
            call enqueue_packet(src,dst,pkt);
            is_ping_packet_received(dst,pkt) := false;
            ping_packet_forwarded_last_round(dst) := ping_packet_forwarded_last_round(dst) + 1;
        }

        action replay_to_client(src:ip.endpoint,dst:ip.endpoint,pkt:packet.ping_packet)
        around replay_to_client(src:ip.endpoint,dst:ip.endpoint,pkt:packet.ping_packet) {
            # require _generating;
            require pkt.payload.end > 0;
            require is_ping_packet_received(dst,pkt);
            require is_ping_packet_received(dst,pkt);
            require mim_agent.nat_configured;
            require src = mim_agent.ep_server & dst = mim_agent.ep_client;
            require src ~= dst;
            ...
            call enqueue_packet(src,dst,pkt);
            is_ping_packet_received(dst,pkt) := true;
            ping_packet_forwarded_last_round(dst) := ping_packet_forwarded_last_round(dst) + 1;
        }

        action replay_to_server(src:ip.endpoint,dst:ip.endpoint,pkt:packet.ping_packet)
        around replay_to_server(src:ip.endpoint,dst:ip.endpoint,pkt:packet.ping_packet) {
            # require _generating;
            require pkt.payload.end > 0;
            require is_ping_packet_received(dst,pkt);
            require mim_agent.nat_configured;
            require src = mim_agent.ep_client & dst = mim_agent.ep_server;
            require src ~= dst;
            ...
            call enqueue_packet(src,dst,pkt);
            is_ping_packet_received(dst,pkt) := true;
            ping_packet_forwarded_last_round(dst) := ping_packet_forwarded_last_round(dst) + 1;
        }

        action modify(src:ip.endpoint,dst:ip.endpoint,pkt:packet.ping_packet)
        around modify(src:ip.endpoint,dst:ip.endpoint,pkt:packet.ping_packet) {
            # require _generating;
            require pkt.payload.end > 0;
            require mim_agent.nat_configured;
            require dst = mim_agent.ep_server & src = mim_agent.ep_client | 
                    dst = mim_agent.ep_client & src = mim_agent.ep_server;
            require is_ping_packet_received(dst,pkt);
            require src ~= dst;
            ...
            call enqueue_packet(src,dst,pkt);
            is_ping_packet_received(dst,pkt) := false;
            ping_packet_forwarded_last_round(dst) := ping_packet_forwarded_last_round(dst) + 1;
        }   
    }
}


function ping_packets_received_last_round(C:ip.endpoint) : packet.ping_packet.arr 
function ping_packet_received_last_round(C:ip.endpoint,P:stream_pos) : packet.ping_packet
relation is_ping_packet_received(C:ip.endpoint, P:packet.ping_packet) 
relation ping_packet_forwarded(C:ip.endpoint, P:packet.ping_packet)
function ping_packet_forwarded_last_round(C:ip.endpoint) : stream_pos

after init {
    ping_packets_received_last_round(C) := packet.ping_packet.arr.empty;
}

after enqueue_packet(src:ip.endpoint,dst:ip.endpoint,pkt:packet) {
    if some(cf:packet.ping_packet) pkt *> cf  {
        ping_packet_forwarded(dst,cf) := true;
    } 
    call show_num_queued_packets(dst,num_queued_packets(dst));
    call show_num_packets_received_last_round(dst,num_packets_received_last_round(dst));
}

after receiving_packet(src:ip.endpoint,dst:ip.endpoint,pkt:packet, pkt_num: stream_pos) {
    if some(cf:packet.ping_packet) pkt *> cf  {
        ping_packet_received_last_round(dst,pkt_num)  := cf;
        is_ping_packet_received(dst,cf)               := true;
        ping_packets_received_last_round(dst)         := ping_packets_received_last_round(dst).append(cf);
    } 
}

after update_received_packet(src:ip.endpoint,dst:ip.endpoint) {
    # is_ping_packet_received(dst) := false;
    ping_packets_received_last_round(dst) := packet.ping_packet.arr.empty;
    ping_packet_forwarded_last_round(dst) := 0;
}