#lang ivy1.7


include ping_byte_stream
include collections
include ping_frame
include apt_packet

object packet = {
    
    ...

    object malicious_ping_packet = {
        # Ping ping_frames contain no data, check peers still alive
        variant this of packet = struct {
            payload : ping_frame.arr
        }
        instance idx : unbounded_sequence
        instance arr : array(idx,this) 
    }    
}

###
# Malicious ping packet
###

# Normal behavior

object packet = {
    ...

    object malicious_ping_packet = {
        ...

        around handle(src:ip.endpoint,dst:ip.endpoint, p:packet.malicious_ping_packet) = {
            require num_queued_frames = 2; # [7]
            require pkt.payload = queued_frames;

            ...

            queued_frames := ping_frame.arr.empty;
            num_queued_frames := 0;
        
        }
    }
}

# 1. Denial-of-Service (DoS) Attacks

object packet = {
    ...

    object malicious_ping_packet = {
        ...

        around flood(src:ip.endpoint,dst:ip.endpoint, p:packet.malicious_ping_packet) = {
            require num_queued_frames > 10; # [7]
            require pkt.payload = queued_frames;

            ...

            queued_frames := ping_frame.arr.empty;
            num_queued_frames := 0;
        }
    }
}