#lang ivy1.7

include order
include file
include bgp_shim
include ivy_bgp_speaker_behavior

relation slept_bgp

after init {
    getsock(bgp_impl_instance.ep.addr) :=  net.connect(endpoint_id.ivy_speaker, endpoint_id.impl_speaker, bgp_impl_instance.ep.addr);
    pend(bgp_impl_instance.ep.addr) := true;
    slept_bgp := false;
}


before bgp_open_message_event(src:bgp_id,dst:bgp_id,bgp_message:bgp_open_message){
    if _generating {

    }
}

before bgp_update_message_event(src:bgp_id,dst:bgp_id,bgp_message:bgp_update_message){
    if _generating {
        require origin_present(src);
    }
}

before bgp_keepalive_message_event(src:bgp_id,dst:bgp_id,bgp_message:bgp_keepalive_message){
    if _generating {

    }
}

before bgp_notification_message_event(src:bgp_id,dst:bgp_id,bgp_message:bgp_notification_message){
    if _generating {

    }
}

export bgp_open_message_event
export bgp_update_message_event
export bgp_keepalive_message_event
export bgp_notification_message_event
export path_attr.origin.handle
export path_attr.as_path.handle
export path_attr.next_hop.handle

# export speaker_send_event

export action _finalize = {
    require conn_state(bgp_impl_instance.bgpid) = bgp_connection_state.established
          | conn_state(bgp_impl_instance.bgpid) = bgp_connection_state.idle;
    require open_message_recv(bgp_impl_instance.bgpid);
    require ~received_unexpected_notification; # [rfc4271:6]
}
