#lang ivy1.7

include order
include file
# include quic_locale
include apt_quic_endpoint
include ivy_attacker

# TODO create socket for client & server
# TODO associate these data to the entities itself
var sock_attacker : quic_net.socket

instance attacker_agent : endpoint.client_attacker_endpoint.attacker_quic_ep(
    malicious_client_addr,
    malicious_client_port,
    server_port,true,true)

