#lang ivy1.7

include order
include quic_infer
include file
include quic_shim
include ivy_target

# include quic_locale
include random_value

include quic_endpoint

parameter target_addr : ip.addr = 0x0a000401
parameter target_port : ip.port = 4430

parameter target_alt_addr : ip.addr = 0x0a000401
parameter target_alt_port : ip.port = 4430

# TODO
parameter client_vn_addr : ip.addr = 0x0a000401
parameter client_port_vn : ip.port = 4430

parameter is_target : bool = false

instance target_agent : endpoint.target_ep(target_addr,target_port)
 
# An ip endpoint for the client to migrate to. TODO

# a socket for the server

var sock_target : quic_net.socket

# Open a server socket to listen on and create an instance of TLS.
# TODO: we should have one instance of TLS per connection




