#lang ivy1.7

include order
include quic_infer
include file
include quic_shim
# include quic_locale
include random_value

include ivy_mim

include quic_endpoint

instance mim_server_target : endpoint.server_quic(server_addr,server_port)
instance mim_client_target : endpoint.client_quic(0,0)
instance fake_client :       endpoint.client_quic(0,0)

# TODO update packet src port/dst port for invisible on network and host
 
# An ip endpoint for the client to migrate to. TODO

# a socket for the server

var sock_mim_server : net.socket
var sock_mim_client : net.socket

# Open a server socket to listen on and create an instance of TLS.
# TODO: we should have one instance of TLS per connection

after init {
    malicious_packet_send := false;
}


# udp && (udp.srcport == 4443 || udp.dstport == 4443 || udp.srcport == 4440 || udp.dstport == 4440 )