#lang ivy1.7

include order
include file
# include random_value

include ivy_minip_mim
include ivy_minip_target
include ivy_minip_attacker

include ivy_minip_shim
include ivy_minip_shim_mim

include ivy_man_in_the_middle_minip_behavior


# NB: need bigger timeout (at least 90 sec)

after init {
    is_mim_standalone := true;
    call mim_agent.configure_NAT_attack_bidir;
}


object packet = {
    ...
    
    object ping_packet = {
        ...
        before forward_to_client(src:ip.endpoint,dst:ip.endpoint,pkt:packet.ping_packet.arr) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require mim_agent.ep_client.addr ~= 0;  # must have a client address to send to
                require src = mim_agent.ep_server;
                require dst = mim_agent.ep_client;
                require pkt = mim_agent.ppkt_to_be_forwarded_to_client(mim_agent.last_packet_forwarded_to(mim_agent.ep_client)); # TODO check
            } 
        }
        
        before forward_to_server(src:ip.endpoint,dst:ip.endpoint,pkt:packet.ping_packet.arr) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require mim_agent.ep_server.addr ~= 0;  # must have a client address to send to
                require dst = mim_agent.ep_server;
                require src = mim_agent.ep_client;
                require pkt = mim_agent.ppkt_to_be_forwarded_to_server(mim_agent.last_packet_forwarded_to(mim_agent.ep_server)); # TODO check       
            } 
        }
    }
}

import action show_last_cppkt_forwarded_to_client_debug_event(x:stream_pos)
import action show_last_cppkt_forwarded_to_server_debug_event(x:stream_pos)

export packet.ping_packet.forward_to_client
export packet.ping_packet.forward_to_server

attribute packet.ping_packet.forward_to_server.weight = "5"
attribute packet.ping_packet.forward_to_client.weight = "15"


# Final check
#
# When the test is complete, the tester calls the special action `_finalize`.
# We use this action to make some heuristic checks, for example that some
# data was actually received from the server. We can add advice to this
# action with additional checks.

export action _finalize = {
    # chris TODO 
    call mim_agent.reset_NAT;
    require mim_agent.last_packet_forwarded_to(mim_agent.ep_server) > 0;
    require mim_agent.last_packet_forwarded_to(mim_agent.ep_client) > 0;
    require mim_agent.last_packet_forwarded_to(mim_agent.ep_client) = mim_agent.cppkt_forwarded_to_client;
    require mim_agent.last_packet_forwarded_to(mim_agent.ep_server) = mim_agent.cppkt_forwarded_to_server;
}


