#lang ivy1.7

include order
include file
# include random_value

include ivy_quic_mim
include ivy_quic_target
include ivy_quic_attacker

include ivy_quic_shim
include ivy_quic_shim_mim

include ivy_man_in_the_middle_quic_behavior

include ivy_quic_client_standard_tp

# NB: need bigger timeout (at least 90 sec)

after init {
    is_mim_standalone := true;
    call mim_agent.configure_NAT_attack_in;
    call mim_agent.configure_NAT_attack_out;
}

export packet.forward_to
attribute packet.forward_to.weight = "100"

object packet = {
    ...
    
    object quic_packet = {
        ...
        before replay_to_client(src:ip.endpoint,dst:ip.endpoint,pkt:packet.quic_packet) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require pkt.ptype       = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).ptype;
                require pkt.pversion    = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).pversion;
                require pkt.dst_cid     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).dst_cid;
                require pkt.src_cid     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).src_cid;
                require pkt.token       = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).token;
                require pkt.seq_num     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).seq_num;
                require pkt.payload     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).payload;
            } 
        }

        before replay_to_server(src:ip.endpoint,dst:ip.endpoint,pkt:packet.quic_packet) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require pkt.ptype       = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).ptype;
                require pkt.pversion    = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).pversion;
                require pkt.dst_cid     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).dst_cid;
                require pkt.src_cid     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).src_cid;
                require pkt.token       = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).token;
                require pkt.seq_num     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).seq_num;
                require pkt.payload     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).payload;
            } 
        }

        before forward_to_client(src:ip.endpoint,dst:ip.endpoint,pkt:packet.quic_packet) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require ~quic_packet_forwarded(dst,pkt);
                require pkt.ptype       = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).ptype;
                require pkt.pversion    = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).pversion;
                require pkt.dst_cid     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).dst_cid;
                require pkt.src_cid     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).src_cid;
                require pkt.token       = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).token;
                require pkt.seq_num     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).seq_num;
                require pkt.payload     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).payload;
            } 
        }

        before forward_to_server(src:ip.endpoint,dst:ip.endpoint,pkt:packet.quic_packet) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require ~quic_packet_forwarded(dst,pkt);
                require pkt.ptype       = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).ptype;
                require pkt.pversion    = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).pversion;
                require pkt.dst_cid     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).dst_cid;
                require pkt.src_cid     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).src_cid;
                require pkt.token       = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).token;
                require pkt.seq_num     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).seq_num;
                require pkt.payload     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).payload;
            } 
        }

        before modify(src:ip.endpoint,dst:ip.endpoint,pkt:packet.quic_packet) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require pkt.ptype       = quic_packet_type.one_rtt |
                        pkt.ptype       = quic_packet_type.zero_rtt |
                        pkt.ptype       = quic_packet_type.handshake |
                        pkt.ptype       = quic_packet_type.retry |
                        pkt.ptype       = quic_packet_type.initial;

                require pkt.pversion    = 0x00000000 | 
                        pkt.pversion    = 0x00000001 |
                        pkt.pversion    = 0xff000022 |
                        pkt.pversion    = 0xff00001d |
                        pkt.pversion    = 0xff00001c |
                        pkt.pversion    = 0xff00001b |
                        (pkt.pversion    ~= 0x00000000 & pkt.pversion    ~= 0x00000001 &
                         pkt.pversion    ~= 0xff000022 & pkt.pversion    ~= 0xff00001d &
                         pkt.pversion    ~= 0xff00001c & pkt.pversion    ~= 0xff00001b);
                
                require (pkt.dst_cid     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).dst_cid &
                         pkt.src_cid     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).src_cid) |
                        (pkt.dst_cid     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).src_cid &
                         pkt.src_cid     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).dst_cid);

                require (pkt.token       = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).token) | 
                        (pkt.token.end >= 0);

                require pkt.seq_num     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).seq_num |
                        pkt.seq_num     < quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).seq_num |
                        pkt.seq_num     > quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).seq_num;

                require pkt.payload     = quic_packet_received_last_round(dst,quic_packet_forwarded_last_round(dst)).payload |
                                          pkt.payload.end >= 0;
            } 
        }
    }
}



export packet.quic_packet.forward_to_server
export packet.quic_packet.forward_to_client

attribute packet.quic_packet.forward_to_server.weight = "15"
attribute packet.quic_packet.forward_to_client.weight = "15"

# export packet.quic_packet.replay_to_client
# export packet.quic_packet.replay_to_server

# attribute packet.quic_packet.replay_to_server.weight = "5"
# attribute packet.quic_packet.replay_to_client.weight = "5"

# export packet.quic_packet.modify

# attribute packet.quic_packet.modify.weight = "5"

import action show_last_cppkt_forwarded_to_client_debug_event(x:stream_pos)
import action show_last_cppkt_forwarded_to_server_debug_event(x:stream_pos)


object packet = {
    ...
    
    object encrypted_quic_packet = {
        ...

        before replay_to_client(src:ip.endpoint,dst:ip.endpoint,pkt:packet.encrypted_quic_packet) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require pkt.head_byte   = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).head_byte;
                require pkt.pversion    = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).pversion;
                require pkt.dst_cid     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).dst_cid;
                require pkt.src_cid     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).src_cid;
                require pkt.token_len   = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).token_len;
                require pkt.token       = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).token;
                require pkt.payload_len = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).payload_len;
                require pkt.seq_num     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).seq_num;
                require pkt.payload     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).payload;
            } 
        }

        before replay_to_server(src:ip.endpoint,dst:ip.endpoint,pkt:packet.encrypted_quic_packet) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require pkt.head_byte   = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).head_byte;
                require pkt.pversion    = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).pversion;
                require pkt.dst_cid     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).dst_cid;
                require pkt.src_cid     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).src_cid;
                require pkt.token_len   = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).token_len;
                require pkt.token       = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).token;
                require pkt.payload_len = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).payload_len;
                require pkt.seq_num     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).seq_num;
                require pkt.payload     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).payload;
            } 
        }

        before forward_to_client(src:ip.endpoint,dst:ip.endpoint,pkt:packet.encrypted_quic_packet) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require ~encrypted_quic_packet_forwarded(dst,pkt);
                require pkt.head_byte   = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).head_byte;
                require pkt.pversion    = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).pversion;
                require pkt.dst_cid     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).dst_cid;
                require pkt.src_cid     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).src_cid;
                require pkt.token_len   = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).token_len;
                require pkt.token       = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).token;
                require pkt.payload_len = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).payload_len;
                require pkt.seq_num     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).seq_num;
                require pkt.payload     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).payload;
            } 
        }

        before forward_to_server(src:ip.endpoint,dst:ip.endpoint,pkt:packet.encrypted_quic_packet) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require ~encrypted_quic_packet_forwarded(dst,pkt);
                require pkt.head_byte   = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).head_byte;
                require pkt.pversion    = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).pversion;
                require pkt.dst_cid     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).dst_cid;
                require pkt.src_cid     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).src_cid;
                require pkt.token_len   = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).token_len;
                require pkt.token       = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).token;
                require pkt.payload_len = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).payload_len;
                require pkt.seq_num     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).seq_num;
                require pkt.payload     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).payload;
            } 
        }

        before modify(src:ip.endpoint,dst:ip.endpoint,pkt:packet.encrypted_quic_packet) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require pkt.head_byte   = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).head_byte;
                
                require pkt.pversion    = 0x00000000 | 
                        pkt.pversion    = 0x00000001 |
                        pkt.pversion    = 0xff000022 |
                        pkt.pversion    = 0xff00001d |
                        pkt.pversion    = 0xff00001c |
                        pkt.pversion    = 0xff00001b |
                        (pkt.pversion    ~= 0x00000000 & pkt.pversion    ~= 0x00000001 &
                         pkt.pversion    ~= 0xff000022 & pkt.pversion    ~= 0xff00001d &
                         pkt.pversion    ~= 0xff00001c & pkt.pversion    ~= 0xff00001b);
                
                require (pkt.dst_cid     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).dst_cid &
                         pkt.src_cid     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).src_cid) |
                        (pkt.dst_cid     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).src_cid &
                         pkt.src_cid     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).dst_cid);

                require (pkt.token_len   = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).token_len &
                         pkt.token       = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).token) | 
                        (pkt.token_len   > 0  & pkt.token.end > 0);

                require pkt.payload_len = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).payload_len;
                
                require pkt.seq_num     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).seq_num |
                        pkt.seq_num     < encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).seq_num |
                        pkt.seq_num     > encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).seq_num;
                
                require pkt.payload     = encrypted_quic_packet_received_last_round(dst,encrypted_quic_packet_forwarded_last_round(dst)).payload;
            } 
        }
    }
}

export packet.encrypted_quic_packet.forward_to_server
export packet.encrypted_quic_packet.forward_to_client

attribute packet.encrypted_quic_packet.forward_to_server.weight = "15"
attribute packet.encrypted_quic_packet.forward_to_client.weight = "15"

# export packet.encrypted_quic_packet.replay_to_client
# export packet.encrypted_quic_packet.replay_to_server

# attribute packet.encrypted_quic_packet.replay_to_server.weight = "5"
# attribute packet.encrypted_quic_packet.replay_to_client.weight = "5"

# export packet.encrypted_quic_packet.modify

# attribute packet.encrypted_quic_packet.modify.weight = "5"

object packet = {
    ...
    
    object random_padding_encrypted_quic_packet = {
        ...

        before replay_to_client(src:ip.endpoint,dst:ip.endpoint,pkt:packet.random_padding_encrypted_quic_packet) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require pkt.payload = random_padding_encrypted_quic_packet_received_last_round(dst,random_padding_encrypted_quic_packet_forwarded_last_round(dst)).payload;
            } 
        }

        before replay_to_server(src:ip.endpoint,dst:ip.endpoint,pkt:packet.random_padding_encrypted_quic_packet) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require pkt.payload = random_padding_encrypted_quic_packet_received_last_round(dst,random_padding_encrypted_quic_packet_forwarded_last_round(dst)).payload;
            } 
        }

        before forward_to_client(src:ip.endpoint,dst:ip.endpoint,pkt:packet.random_padding_encrypted_quic_packet) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require ~random_padding_encrypted_quic_packet_forwarded(dst,pkt);
                require pkt.payload = random_padding_encrypted_quic_packet_received_last_round(dst,random_padding_encrypted_quic_packet_forwarded_last_round(dst)).payload;
            } 
        }

        before forward_to_server(src:ip.endpoint,dst:ip.endpoint,pkt:packet.random_padding_encrypted_quic_packet) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require ~random_padding_encrypted_quic_packet_forwarded(dst,pkt);
                require pkt.payload = random_padding_encrypted_quic_packet_received_last_round(dst,random_padding_encrypted_quic_packet_forwarded_last_round(dst)).payload;
            } 
        }

        before modify(src:ip.endpoint,dst:ip.endpoint,pkt:packet.random_padding_encrypted_quic_packet) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require pkt.payload = random_padding_encrypted_quic_packet_received_last_round(dst,random_padding_encrypted_quic_packet_forwarded_last_round(dst)).payload | 
                                      pkt.payload.end >= 0;
            } 
        }
    }
}

export packet.random_padding_encrypted_quic_packet.forward_to_server
export packet.random_padding_encrypted_quic_packet.forward_to_client

attribute packet.random_padding_encrypted_quic_packet.forward_to_server.weight = "15"
attribute packet.random_padding_encrypted_quic_packet.forward_to_client.weight = "15"

# export packet.random_padding_encrypted_quic_packet.replay_to_client
# export packet.random_padding_encrypted_quic_packet.replay_to_server

# attribute packet.random_padding_encrypted_quic_packet.replay_to_server.weight = "5"
# attribute packet.random_padding_encrypted_quic_packet.replay_to_client.weight = "5"

# export packet.random_padding_encrypted_quic_packet.modify

# attribute packet.random_padding_encrypted_quic_packet.modify.weight = "5"

object packet = {
    ...
    
    object encrypted_short_quic_packet = {
        ...

        before replay_to_client(src:ip.endpoint,dst:ip.endpoint,pkt:packet.encrypted_short_quic_packet) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require pkt.head_byte   = encrypted_short_quic_packet_received_last_round(dst,encrypted_short_quic_packet_forwarded_last_round(dst)).head_byte;
                require pkt.dst_cid     = encrypted_short_quic_packet_received_last_round(dst,encrypted_short_quic_packet_forwarded_last_round(dst)).dst_cid;
                require pkt.payload     = encrypted_short_quic_packet_received_last_round(dst,encrypted_short_quic_packet_forwarded_last_round(dst)).payload;
            } 
        }

        before replay_to_server(src:ip.endpoint,dst:ip.endpoint,pkt:packet.encrypted_short_quic_packet) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require pkt.head_byte   = encrypted_short_quic_packet_received_last_round(dst,encrypted_short_quic_packet_forwarded_last_round(dst)).head_byte;
                require pkt.dst_cid     = encrypted_short_quic_packet_received_last_round(dst,encrypted_short_quic_packet_forwarded_last_round(dst)).dst_cid;
                require pkt.payload     = encrypted_short_quic_packet_received_last_round(dst,encrypted_short_quic_packet_forwarded_last_round(dst)).payload;
            } 
        }

        before forward_to_client(src:ip.endpoint,dst:ip.endpoint,pkt:packet.encrypted_short_quic_packet) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require ~encrypted_short_quic_packet_forwarded(dst,pkt);
                require pkt.head_byte   = encrypted_short_quic_packet_received_last_round(dst,encrypted_short_quic_packet_forwarded_last_round(dst)).head_byte;
                require pkt.dst_cid     = encrypted_short_quic_packet_received_last_round(dst,encrypted_short_quic_packet_forwarded_last_round(dst)).dst_cid;
                require pkt.payload     = encrypted_short_quic_packet_received_last_round(dst,encrypted_short_quic_packet_forwarded_last_round(dst)).payload;
            } 
        }

        before forward_to_server(src:ip.endpoint,dst:ip.endpoint,pkt:packet.encrypted_short_quic_packet) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require ~encrypted_short_quic_packet_forwarded(dst,pkt);
                require pkt.head_byte   = encrypted_short_quic_packet_received_last_round(dst,encrypted_short_quic_packet_forwarded_last_round(dst)).head_byte;
                require pkt.dst_cid     = encrypted_short_quic_packet_received_last_round(dst,encrypted_short_quic_packet_forwarded_last_round(dst)).dst_cid;
                require pkt.payload     = encrypted_short_quic_packet_received_last_round(dst,encrypted_short_quic_packet_forwarded_last_round(dst)).payload;
            } 
        }

        before modify(src:ip.endpoint,dst:ip.endpoint,pkt:packet.encrypted_short_quic_packet) {
            call show_last_cppkt_forwarded_to_server_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server));
            call show_last_cppkt_forwarded_to_client_debug_event(mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client));
            if _generating {
                require pkt.head_byte   = encrypted_short_quic_packet_received_last_round(dst,encrypted_short_quic_packet_forwarded_last_round(dst)).head_byte;

                require (pkt.dst_cid    = encrypted_short_quic_packet_received_last_round(dst,encrypted_short_quic_packet_forwarded_last_round(dst)).dst_cid | 
                         pkt.dst_cid   ~= encrypted_short_quic_packet_received_last_round(dst,encrypted_short_quic_packet_forwarded_last_round(dst)).dst_cid);

                require pkt.payload     = encrypted_short_quic_packet_received_last_round(dst,encrypted_short_quic_packet_forwarded_last_round(dst)).payload;
            } 
        }
    }
}


export packet.encrypted_short_quic_packet.forward_to_server
export packet.encrypted_short_quic_packet.forward_to_client

attribute packet.encrypted_short_quic_packet.forward_to_server.weight = "15"
attribute packet.encrypted_short_quic_packet.forward_to_client.weight = "15"

# export packet.encrypted_short_quic_packet.replay_to_client
# export packet.encrypted_short_quic_packet.replay_to_server

# attribute packet.encrypted_short_quic_packet.replay_to_server.weight = "5"
# attribute packet.encrypted_short_quic_packet.replay_to_client.weight = "5"

# export packet.encrypted_short_quic_packet.modify

# attribute packet.encrypted_short_quic_packet.modify.weight = "5"

# Final check
#
# When the test is complete, the tester calls the special action `_finalize`.
# We use this action to make some heuristic checks, for example that some
# data was actually received from the server. We can add advice to this
# action with additional checks.

export action _finalize = {
    # chris TODO 
    call mim_agent.reset_NAT;
    require mim_agent.last_packet_forwarded_to(mim_agent.ep_server) > 0 | mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server) > 0;
    require mim_agent.last_packet_forwarded_to(mim_agent.ep_client) > 0 | mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client) > 0;
    require mim_agent.last_packet_forwarded_to(mim_agent.ep_client) = mim_agent.number_packet_forwarded_to(mim_agent.ep_client) | mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_client) = mim_agent.number_encrypted_packet_forwarded_to(mim_agent.ep_client);
    require mim_agent.last_packet_forwarded_to(mim_agent.ep_server) = mim_agent.number_packet_forwarded_to(mim_agent.ep_server) | mim_agent.last_encrypted_packet_forwarded_to(mim_agent.ep_server) = mim_agent.number_encrypted_packet_forwarded_to(mim_agent.ep_server);
}

